apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphacar-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphacar-frontend
  template:
    metadata:
      labels:
        app: alphacar-frontend
    spec:
      containers:
      - name: alphacar-frontend
        image: 192.168.56.200:30002/alphacar/alphacar-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alphacar-frontend-service
  namespace: default
spec:
  selector:
    app: alphacar-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
